"use client";
import { useState } from "react";
import type { KidsGameDefinition } from "@/data/kidsGames";
import LanguageNarrator from "./LanguageNarrator";
import AITeacherHelp from "./AITeacherHelp";

const bank:Record<string,{q:string;options:string[];answer:string;explain:string}[]>={
 Maths:[{q:"What is 7 + 5?",options:["10","11","12","13"],answer:"12",explain:"Seven plus five equals twelve."},{q:"What is 4 × 3?",options:["7","10","12","14"],answer:"12",explain:"Four groups of three make twelve."},{q:"Which is one half?",options:["1/2","1/3","2/3","3/4"],answer:"1/2",explain:"One half means one of two equal parts."}],
 English:[{q:"Which word is spelled correctly?",options:["becos","because","becaus","beacause"],answer:"because",explain:"Because is spelled b-e-c-a-u-s-e."},{q:"Which word is a verb?",options:["happy","jump","blue","table"],answer:"jump",explain:"Jump is an action word, so it is a verb."},{q:"Choose the synonym of big.",options:["tiny","large","slow","quiet"],answer:"large",explain:"Large means nearly the same as big."}],
 Science:[{q:"Which planet do we live on?",options:["Mars","Earth","Venus","Jupiter"],answer:"Earth",explain:"Earth is our home planet."},{q:"Which organ pumps blood?",options:["Heart","Lung","Stomach","Skin"],answer:"Heart",explain:"The heart pumps blood around the body."},{q:"What do plants need to make food?",options:["Sunlight","Plastic","Metal","Sand only"],answer:"Sunlight",explain:"Plants use sunlight during photosynthesis."}],
 Geography:[{q:"How many continents are commonly taught?",options:["5","6","7","8"],answer:"7",explain:"Seven continents are commonly taught."},{q:"Which is an ocean?",options:["Sahara","Pacific","Alps","Amazon"],answer:"Pacific",explain:"The Pacific is the largest ocean."},{q:"Paris is the capital of which country?",options:["France","Italy","Spain","Belgium"],answer:"France",explain:"Paris is the capital of France."}],
 Logic:[{q:"What comes next: 2, 4, 6, ?",options:["7","8","9","10"],answer:"8",explain:"The pattern adds two each time."},{q:"Which does not belong?",options:["Circle","Square","Triangle","Banana"],answer:"Banana",explain:"The first three are shapes."},{q:"If all bloops are blue, a red thing cannot be a...",options:["bloop","colour","thing","shape"],answer:"bloop",explain:"All bloops are blue, so a red thing is not a bloop."}],
 Classic:[]
};

function QuizGame({game}:{game:KidsGameDefinition}){ const qs=bank[game.subject]??bank.Logic; const [i,setI]=useState(0); const [score,setScore]=useState(0); const [feedback,setFeedback]=useState(""); const item=qs[i%qs.length]; const choose=(a:string)=>{const ok=a===item.answer;setFeedback(ok?`✅ ${item.explain}`:"Try again. Ask the Help Teacher for a hint.");if(ok){setScore(s=>s+1);setTimeout(()=>{setI(n=>n+1);setFeedback("")},650)}}; return <div className="game-stage"><div className="game-score">⭐ Score {score}</div><h2>{item.q}</h2><div className="answer-grid">{item.options.map(o=><button key={o} type="button" onClick={()=>choose(o)}>{o}</button>)}</div>{feedback&&<p className="game-feedback">{feedback}</p>}<AITeacherHelp title={game.title} objective={game.objective} question={item.q}/><LanguageNarrator text={`${game.title}. ${item.q}`}/></div> }
function TicTacToe(){const [b,setB]=useState<string[]>(Array(9).fill(""));const winner=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(x=>b[x[0]]&&b[x[0]]===b[x[1]]&&b[x[1]]===b[x[2]]);const play=(n:number)=>{if(b[n]||winner)return;const next=[...b];next[n]="X";const empty=next.map((v,i)=>v? -1:i).filter(i=>i>=0);if(empty.length){next[empty[0]]="O"}setB(next)};return <div className="game-stage"><h2>{winner?`${b[winner[0]]} wins!`:b.every(Boolean)?"Draw game":"Your turn: X"}</h2><div className="ttt-board">{b.map((v,i)=><button key={i} onClick={()=>play(i)}>{v}</button>)}</div><button className="button button-secondary" onClick={()=>setB(Array(9).fill(""))}>New game</button><AITeacherHelp title="Tic-Tac-Toe" objective="plan ahead and make a line of three"/></div>}
function Memory(){const cards=["🐼","🚀","🍎","⭐","🚀","⭐","🐼","🍎"];const [open,setOpen]=useState<number[]>([]);const [done,setDone]=useState<number[]>([]);const flip=(i:number)=>{if(open.includes(i)||done.includes(i)||open.length===2)return;const n=[...open,i];setOpen(n);if(n.length===2)setTimeout(()=>{if(cards[n[0]]===cards[n[1]])setDone(d=>[...d,...n]);setOpen([])},600)};return <div className="game-stage"><h2>Match all the pairs</h2><div className="memory-board">{cards.map((c,i)=><button key={i} onClick={()=>flip(i)}>{open.includes(i)||done.includes(i)?c:"?"}</button>)}</div><p>{done.length/2} of 4 pairs</p><AITeacherHelp title="Memory Match" objective="remember where matching cards are hidden"/></div>}
function Snakes(){const [pos,setPos]=useState(1);const [roll,setRoll]=useState(0);const jump:Record<number,number>={3:11,8:15,14:5,18:9};const go=()=>{const d=Math.floor(Math.random()*6)+1;setRoll(d);setPos(p=>Math.min(20,jump[Math.min(20,p+d)]??Math.min(20,p+d)))};return <div className="game-stage"><h2>{pos===20?"🏆 You reached 20!":"Reach square 20"}</h2><div className="snake-board">{Array.from({length:20},(_,k)=>20-k).map(n=><div key={n} className={n===pos?"player-square":""}>{n}{n===3||n===8?" 🪜":n===14||n===18?" 🐍":""}</div>)}</div><button className="button button-primary" onClick={go} disabled={pos===20}>🎲 Roll dice {roll?`(${roll})`:""}</button><AITeacherHelp title="Snakes & Ladders" objective="count forward and understand number order"/></div>}
export default function UniversalKidsGame({game}:{game:KidsGameDefinition}){if(game.type==="tic-tac-toe")return <TicTacToe/>;if(game.type==="memory")return <Memory/>;if(game.type==="snakes-ladders")return <Snakes/>;return <QuizGame game={game}/>}
