"use client";
import {useCallback,useEffect,useState} from "react";
import type {GlobalGame} from "@/data/games";

type PieceType="K"|"Q"|"R"|"B"|"N"|"P";
type Piece={type:PieceType;color:"w"|"b"}|null;
const glyph:Record<string,string>={wK:"♔",wQ:"♕",wR:"♖",wB:"♗",wN:"♘",wP:"♙",bK:"♚",bQ:"♛",bR:"♜",bB:"♝",bN:"♞",bP:"♟"};
function initialChess():Piece[]{const back:PieceType[]=["R","N","B","Q","K","B","N","R"];return [...back.map(type=>({type,color:"b"} as Piece)),...Array(8).fill({type:"P",color:"b"}),...Array(32).fill(null),...Array(8).fill({type:"P",color:"w"}),...back.map(type=>({type,color:"w"} as Piece))]}
function chessMoves(board:Piece[],from:number){const p=board[from];if(!p)return[];const row=Math.floor(from/8),col=from%8,out:number[]=[];const add=(r:number,c:number)=>{if(r<0||r>7||c<0||c>7)return false;const i=r*8+c;if(!board[i]){out.push(i);return true}if(board[i]?.color!==p.color)out.push(i);return false};const ray=(dr:number,dc:number)=>{let r=row+dr,c=col+dc;while(add(r,c)){r+=dr;c+=dc}};if(p.type==="R"||p.type==="Q")[[1,0],[-1,0],[0,1],[0,-1]].forEach(([a,b])=>ray(a,b));if(p.type==="B"||p.type==="Q")[[1,1],[1,-1],[-1,1],[-1,-1]].forEach(([a,b])=>ray(a,b));if(p.type==="N")[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(([a,b])=>add(row+a,col+b));if(p.type==="K")for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if(a||b)add(row+a,col+b);if(p.type==="P"){const d=p.color==="w"?-1:1,start=p.color==="w"?6:1;const one=(row+d)*8+col;if(row+d>=0&&row+d<=7&&!board[one]){out.push(one);const two=(row+2*d)*8+col;if(row===start&&!board[two])out.push(two)}for(const dc of [-1,1]){const r=row+d,c=col+dc;if(r>=0&&r<8&&c>=0&&c<8){const i=r*8+c;if(board[i]&&board[i]?.color!==p.color)out.push(i)}}}return out}
function Chess(){const [board,setBoard]=useState<Piece[]>(initialChess);const [selected,setSelected]=useState<number|null>(null);const [turn,setTurn]=useState<"w"|"b">("w");const [history,setHistory]=useState<string[]>([]);const moves=selected===null?[]:chessMoves(board,selected);const winner=!board.some(p=>p?.type==="K"&&p.color==="w")?"Black":!board.some(p=>p?.type==="K"&&p.color==="b")?"White":null;const click=(i:number)=>{if(winner)return;const p=board[i];if(selected===null){if(p?.color===turn)setSelected(i);return}if(p?.color===turn){setSelected(i);return}if(!moves.includes(i)){setSelected(null);return}const next=[...board],moving=next[selected]!;next[i]=moving;next[selected]=null;if(moving.type==="P"&&(Math.floor(i/8)===0||Math.floor(i/8)===7))next[i]={...moving,type:"Q"};setBoard(next);setHistory(h=>[`${turn==="w"?"White":"Black"}: ${String.fromCharCode(97+selected%8)}${8-Math.floor(selected/8)} → ${String.fromCharCode(97+i%8)}${8-Math.floor(i/8)}`,...h].slice(0,8));setTurn(turn==="w"?"b":"w");setSelected(null)};return <div className="game-stage global-stage"><div className="global-game-toolbar"><strong>{winner?`🏆 ${winner} wins!`:`${turn==="w"?"White":"Black"} to move`}</strong><button onClick={()=>{setBoard(initialChess());setTurn("w");setSelected(null);setHistory([])}}>New game</button></div><div className="chess-layout"><div className="chess-board" role="grid">{board.map((p,i)=><button key={i} onClick={()=>click(i)} className={`${(Math.floor(i/8)+i%8)%2?"dark":"light"} ${selected===i?"selected":""} ${moves.includes(i)?"legal":""}`} aria-label={`Chess square ${i+1}`}>{p?glyph[p.color+p.type]:""}</button>)}</div><aside className="move-panel"><h3>Move history</h3>{history.length?history.map((h,i)=><p key={i}>{h}</p>):<p>Select a white piece to begin.</p>}<small>Local two-player practice. Castling and en passant are intentionally omitted in this launch version.</small></aside></div></div>}

const C4_ROWS=6,C4_COLS=7;type Disc=0|1|2;function c4Winner(b:Disc[]){for(let r=0;r<C4_ROWS;r++)for(let c=0;c<C4_COLS;c++)for(const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){const v=b[r*C4_COLS+c];if(!v)continue;let ok=true;for(let k=1;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=C4_ROWS||cc<0||cc>=C4_COLS||b[rr*C4_COLS+cc]!==v)ok=false}if(ok)return v}return b.every(Boolean)?3:0}
function ConnectFour(){const [b,setB]=useState<Disc[]>(Array(42).fill(0));const [thinking,setThinking]=useState(false);const win=c4Winner(b);const drop=useCallback((col:number,player:1|2,base=b)=>{for(let r=5;r>=0;r--){const i=r*7+col;if(!base[i]){const n=[...base];n[i]=player;return n}}return null},[b]);const play=(c:number)=>{if(win||thinking)return;const n=drop(c,1);if(!n)return;setB(n);if(!c4Winner(n))setThinking(true)};useEffect(()=>{if(!thinking)return;const t=setTimeout(()=>{setB(cur=>{const choices=[3,2,4,1,5,0,6].filter(c=>cur[c]===0);let next:null|Disc[]=null;for(const c of choices){const n=drop(c,2,cur);if(n&&c4Winner(n)===2){next=n;break}}if(!next)for(const c of choices){const n=drop(c,1,cur);if(n&&c4Winner(n)===1){next=drop(c,2,cur);break}}return next??drop(choices[0],2,cur)??cur});setThinking(false)},350);return()=>clearTimeout(t)},[thinking,drop]);return <div className="game-stage global-stage"><div className="global-game-toolbar"><strong>{win===1?"🎉 You win!":win===2?"Computer wins":win===3?"Draw":thinking?"Computer thinking…":"Your turn"}</strong><button onClick={()=>{setB(Array(42).fill(0));setThinking(false)}}>New game</button></div><div className="connect-controls">{Array.from({length:7},(_,c)=><button key={c} onClick={()=>play(c)} aria-label={`Drop in column ${c+1}`}>↓</button>)}</div><div className="connect-board">{b.map((v,i)=><div key={i} className={`connect-cell disc-${v}`}/>)}</div></div>}

const puzzle=[5,3,0,0,7,0,0,0,0,6,0,0,1,9,5,0,0,0,0,9,8,0,0,0,0,6,0,8,0,0,0,6,0,0,0,3,4,0,0,8,0,3,0,0,1,7,0,0,0,2,0,0,0,6,0,6,0,0,0,0,2,8,0,0,0,0,4,1,9,0,0,5,0,0,0,0,8,0,0,7,9];const solution=[5,3,4,6,7,8,9,1,2,6,7,2,1,9,5,3,4,8,1,9,8,3,4,2,5,6,7,8,5,9,7,6,1,4,2,3,4,2,6,8,5,3,7,9,1,7,1,3,9,2,4,8,5,6,9,6,1,5,3,7,2,8,4,2,8,7,4,1,9,6,3,5,3,4,5,2,8,6,1,7,9];
function Sudoku(){const [b,setB]=useState(puzzle);const [selected,setSelected]=useState<number|null>(null);const complete=b.every((v,i)=>v===solution[i]);const set=(n:number)=>{if(selected===null||puzzle[selected])return;const next=[...b];next[selected]=n;setB(next)};return <div className="game-stage global-stage"><div className="global-game-toolbar"><strong>{complete?"🎉 Puzzle solved!":"Fill every row, column and box"}</strong><button onClick={()=>{setB(puzzle);setSelected(null)}}>Reset</button></div><div className="sudoku-board">{b.map((v,i)=><button key={i} onClick={()=>!puzzle[i]&&setSelected(i)} className={`${puzzle[i]?"given":""} ${selected===i?"selected":""} ${v&&v!==solution[i]?"wrong":""}`}>{v||""}</button>)}</div><div className="number-pad">{[1,2,3,4,5,6,7,8,9,0].map(n=><button key={n} onClick={()=>set(n)}>{n||"⌫"}</button>)}</div></div>}

function compress(row:number[]){const a=row.filter(Boolean);for(let i=0;i<a.length-1;i++)if(a[i]===a[i+1]){a[i]*=2;a.splice(i+1,1)}while(a.length<4)a.push(0);return a}function rotate(b:number[]){return [12,8,4,0,13,9,5,1,14,10,6,2,15,11,7,3].map(i=>b[i])}function addTile(b:number[]){const e=b.map((v,i)=>v? -1:i).filter(i=>i>=0);if(!e.length)return b;const n=[...b];n[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4;return n}
function NumberMerge(){const [b,setB]=useState(()=>addTile(addTile(Array(16).fill(0))));const [score,setScore]=useState(0);const move=useCallback((dir:number)=>{setB(cur=>{let x=[...cur];for(let i=0;i<dir;i++)x=rotate(x);const before=x.reduce((a,v)=>a+v,0);x=[0,1,2,3].flatMap(r=>compress(x.slice(r*4,r*4+4)));for(let i=dir;i<4;i++)x=rotate(x);if(x.some((v,i)=>v!==cur[i])){setScore(s=>s+Math.max(0,x.reduce((a,v)=>a+v,0)-before));return addTile(x)}return cur})},[]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{const map:Record<string,number>={ArrowLeft:0,ArrowDown:1,ArrowRight:2,ArrowUp:3};if(e.key in map){e.preventDefault();move(map[e.key])}};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[move]);return <div className="game-stage global-stage"><div className="global-game-toolbar"><strong>Score {score}</strong><button onClick={()=>{setB(addTile(addTile(Array(16).fill(0))));setScore(0)}}>New game</button></div><div className="merge-board">{b.map((v,i)=><div key={i} data-value={v}>{v||""}</div>)}</div><div className="direction-pad"><button onClick={()=>move(3)}>↑</button><div><button onClick={()=>move(0)}>←</button><button onClick={()=>move(1)}>↓</button><button onClick={()=>move(2)}>→</button></div></div></div>}

type Point={x:number;y:number};const same=(a:Point,b:Point)=>a.x===b.x&&a.y===b.y;
function Snake(){const W=18,H=18;const [body,setBody]=useState<Point[]>([{x:8,y:9},{x:7,y:9},{x:6,y:9}]);const [food,setFood]=useState<Point>({x:13,y:9});const [dir,setDir]=useState<Point>({x:1,y:0});const [running,setRunning]=useState(false);const [dead,setDead]=useState(false);const turn=(x:number,y:number)=>{if(dir.x+x===0&&dir.y+y===0)return;setDir({x,y});setRunning(true)};useEffect(()=>{if(!running||dead)return;const t=setInterval(()=>{setBody(cur=>{const head={x:cur[0].x+dir.x,y:cur[0].y+dir.y};if(head.x<0||head.x>=W||head.y<0||head.y>=H||cur.some(p=>same(p,head))){setDead(true);setRunning(false);return cur}const ate=same(head,food);const next=[head,...cur];if(!ate)next.pop();else{let f={x:Math.floor(Math.random()*W),y:Math.floor(Math.random()*H)};while(next.some(p=>same(p,f)))f={x:Math.floor(Math.random()*W),y:Math.floor(Math.random()*H)};setFood(f)}return next})},130);return()=>clearInterval(t)},[running,dead,dir,food]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{const m:Record<string,Point>={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}};if(m[e.key]){e.preventDefault();turn(m[e.key].x,m[e.key].y)}};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)});const reset=()=>{setBody([{x:8,y:9},{x:7,y:9},{x:6,y:9}]);setFood({x:13,y:9});setDir({x:1,y:0});setDead(false);setRunning(false)};return <div className="game-stage global-stage"><div className="global-game-toolbar"><strong>{dead?"Game over":running?`Score ${body.length-3}`:"Press a direction to start"}</strong><button onClick={reset}>New game</button></div><div className="snake-grid">{Array.from({length:W*H},(_,i)=>{const p={x:i%W,y:Math.floor(i/W)};return <div key={i} className={body.some(s=>same(s,p))?"snake-body":same(food,p)?"snake-food":""}/>})}</div><div className="direction-pad"><button onClick={()=>turn(0,-1)}>↑</button><div><button onClick={()=>turn(-1,0)}>←</button><button onClick={()=>turn(0,1)}>↓</button><button onClick={()=>turn(1,0)}>→</button></div></div></div>}

export default function GlobalGamePlayer({game}:{game:GlobalGame}){if(game.type==="chess")return <Chess/>;if(game.type==="connect-four")return <ConnectFour/>;if(game.type==="sudoku")return <Sudoku/>;if(game.type==="number-merge")return <NumberMerge/>;if(game.type==="snake")return <Snake/>;return null}
