import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import QuizPlayer from "@/components/QuizPlayer";
import { quizLookup, quizzes } from "@/data/quizzes";
import { categoryLookup } from "@/data/categories";
export function generateStaticParams(){return quizzes.map(q=>({slug:q.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const q=quizLookup[slug];if(!q)return{title:"Quiz not found"};return{title:q.seoTitle,description:q.seoDescription,alternates:{canonical:`/quiz/${slug}/`},openGraph:{title:q.seoTitle,description:q.seoDescription,type:"article",url:`https://curioquiz.xyz/quiz/${slug}/`}}}
export default async function QuizPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const q=quizLookup[slug];if(!q)notFound();const c=categoryLookup[q.categorySlug];const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:q.faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <main><section className="section"><div className="page-container"><nav className="breadcrumbs"><Link href="/">Home</Link><span>›</span><Link href="/quizzes/">Quizzes</Link><span>›</span><Link href={`/category/${q.categorySlug}/`}>{c?.title}</Link></nav><header className="page-card quiz-intro"><p className="small-label">{c?.icon} {c?.title} · {q.estimatedTime}</p><h1>{q.title}</h1><p>{q.introduction}</p><p className="notice-box">{q.disclaimer}</p></header><QuizPlayer quiz={q}/><section className="page-card"><h2>Frequently asked questions</h2><div className="faq-list">{q.faqs.map(f=><article className="faq-item" key={f.question}><h3>{f.question}</h3><p>{f.answer}</p></article>)}</div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://curioquiz.xyz/"},{"@type":"ListItem",position:2,name:"Quizzes",item:"https://curioquiz.xyz/quizzes/"},{"@type":"ListItem",position:3,name:q.title,item:`https://curioquiz.xyz/quiz/${q.slug}/`}]})}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/></div></section></main>}
